CREATE DATABASE asianFood;
USE asianFood;

    CREATE TABLE banners (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    imagenUrl VARCHAR(1000) NOT NULL
    );



CREATE TABLE chefs (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(255) NOT NULL,
descripcion VARCHAR(255) NOT NULL, 
imagenUrl VARCHAR(1000) NOT NULL   
);


CREATE TABLE platos (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(255) NOT NULL,
descripcion VARCHAR(255) NOT NULL,
precio VARCHAR(255) NOT NULL,
imagenUrl VARCHAR(1000) NOT NULL
);

CREATE TABLE testimonios (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(255) NOT NULL,
opinion VARCHAR(255) NOT NULL
);



CREATE TABLE usuario (
id INT PRIMARY KEY AUTO_INCREMENT,
nombreUsuario VARCHAR(255) NOT NULL,
passwordUsuario VARCHAR(255) NOT NULL,
correo VARCHAR(255) NOT NULL
);


CREATE TABLE sugerencias (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    correo VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    mensaje VARCHAR(1000) NOT NULL
);